version: '2.2'

services:
  web:
    build:
      context: .
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    volumes:
      - ./:/usr/src/app
    depends_on:
      - pubsub
      - worker

  worker:
    build:
      context: .
    command: ["bin/rails", "worker:run"]
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    volumes:
      - ./:/usr/src/app
    depends_on:
      - pubsub

  subscriber:
    build:
      context: .
    command: ["bin/rails", "subscriber:run"]
    environment:
      - PUBSUB_EMULATOR_HOST=pubsub:8681
    volumes:
      - ./:/usr/src/app
    depends_on:
      - pubsub
      - worker

  pubsub:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - "8681:8681"
